version: '3.8'

services:
  backend:
    build:
      context: ./backend  # Path to the backend folder
      dockerfile: ./docker/Dockerfile
    env_file:
      - ./backend/.env  # Path to your .env file
    volumes:
      #- ~/.cache/:/root/.cahce/
      - /dev/dri:/dev/dri
      - /tmp/.X11-unix/:/tmp/.X11-unix
      - ./:/workspace
    ports:
      - "8000:8000"
    environment:
      - LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/cuda/lib64
    command: [ "app:app", "-k", "uvicorn.workers.UvicornWorker", "-w", "8", "-b", "0.0.0.0:8000", "-t", "1000"]
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]